security:
    enable_authenticator_manager: true

    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        admin_platform_user_provider:
            id: sylius.admin_user_provider.email_or_name_based

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            switch_user: true
            provider: admin_platform_user_provider
            form_login:
                login_path: admin_platform_admin_login
                check_path: admin_platform_admin_login_check
                failure_path: admin_platform_admin_login
                default_target_path: admin_platform_admin_dashboard_index
                use_forward: false
                use_referer: true
            remember_me:
                secret: "%env(APP_SECRET)%"
                name: APP_ADMIN_REMEMBER_ME
                lifetime: 31536000
                remember_me_parameter: _remember_me
            logout:
                path: admin_platform_admin_logout
                target: admin_platform_admin_login

    access_control:
        - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/logout, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_ADMINISTRATION_ACCESS }

when@test:
    security:
        firewalls:
            main:
                entry_point: form_login
                custom_authenticators:
                    - App\Tests\TestBasicAuthenticator
