services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $projectDir: '%kernel.project_dir%'
            $userManager: '@sylius.manager.admin_user'

    App\Tests\Behat\:
        resource: '../tests/Behat/*'

    App\Tests\TestBasicAuthenticator: ~
